node {
    def myGradleContainer = docker.image('gradle:jdk8-alpine')
    myGradleContainer.pull()
    def mymavenContainer = docker.image('maven:3-alpine')
    mymavenContainer.pull()

    stage('prep') {
        git url: 'https://github.com/harshu004/gs-gradle.git'
    }

}
